site_name: eGov4Dev
site_url: https://egov-moldova.github.io/test-docs/
use_directory_urls: true

theme:
    name: material
    language: ro
    logo: assets/logo.png
    favicon: assets/favicon.ico
    icon:
      alternate: material/translate-variant
    palette:
      - scheme: slate
        toggle:
          name: Dark mode
          icon: material/shield-sun-outline
        primary: blue
        accent: indigo
      - scheme: default
        toggle:
          name: Light mode
          icon: material/shield-moon-outline
        primary: blue
        accent: indigo
    features:
      - navigation.tracking
      - navigation.path
      - navigation.indexes 

plugins:
  - search
  - privacy:
      links: true
      links_attr_map:
        target: _blank
      links_noopener: true
      links_noreferrer: true
  - i18n:
      docs_structure: suffix
      languages:
        - locale: ro
          name: Română
          default: true
          build: true
        - locale: en
          name: English
          build: true
          nav_translations:
            Acasă: Home
            Despre: About
            Introducere: Intro
            Principii arhitecturale: Architecture principles
            Produse M: MSuite
            Scenarii de interacțiune: Workflows
            Standardul Soap: Soap standard
            Parcursul integrării: Integration process

extra:
  alternate:
    - name: Română
      link: /test-docs/
      lang: ro
    - name: English
      link: /test-docs/en/
      lang: en
  social:
    - icon: fontawesome/brands/youtube 
      link: https://www.youtube.com/user/eGovCenterMoldova
    - icon: fontawesome/brands/facebook 
      link: https://www.facebook.com/eGovernanceAgency.Moldova
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/e-government-center
    - icon: fontawesome/brands/instagram 
      link: https://www.instagram.com/e_guvernare_moldova/
    - icon: fontawesome/brands/flickr
      link: https://www.flickr.com/photos/201389958@N05/

extra_css:
  - stylesheets/extra.css
  - stylesheets/onest.css
  - stylesheets/table.css

extra_javascript:
  - js/theme-switcher.js
  - js/external-links.js

markdown_extensions:
  - admonition
  - pymdownx.tilde
  
nav:
  - Acasă: index.md
  - Principii arhitecturale:
    - Principii arhitecturale: architecture/index.md
    - Standardul Soap: architecture/soap.md
    - Standardul REST: architecture/rest.md
    - DevOps:
      - DevOps: architecture/devops/index.md
      - Helm: architecture/devops/helm.md
  - Produse M: 
    - Produse M: mservices/mservices_index.md
    - MConnect: mservices/mconnect.md
    - MPay:
      - Introducere: mservices/mpay/mpay_index.md
      - Scenarii de interacțiune:  mservices/mpay/mpay_workflow.md
      - Parcursul integrării:  mservices/mpay/mpay_integration_proccess.md
  - Info:
    - Despre: info/about.md
    - Contacte: info/contacts.md

copyright: © Agenția de Guvernare Electronică. Toate drepturile rezervate. 
