site_name: Documentation

theme:
    name: material
    language: ro
    logo: assets/logo.png
    favicon: assets/favicon.ico
    icon:
      alternate: material/translate-variant
    palette:
      - scheme: slate
        toggle:
          name: Dark mode
          icon: material/shield-sun-outline
        primary: light blue
        accent: blue
      - scheme: default
        toggle:
          name: Light mode
          icon: material/shield-moon-outline
        primary: light blue
        accent: blue

plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: ro
          name: Română
          default: true
          build: true
        - locale: en
          name: English
          build: true
          nav_translations:
            Acasă: Home
            Despre: About
extra:
  alternate:
    - name: Română
      link: /
      lang: ro
    - name: English
      link: /en/
      lang: en
  social:
    - icon: fontawesome/brands/youtube 
      link: https://www.youtube.com/user/eGovCenterMoldova
    - icon: fontawesome/brands/facebook 
      link: https://www.facebook.com/eGovernanceAgency.Moldova
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/e-government-center
    - icon: fontawesome/brands/instagram 
      link: https://www.instagram.com/e_guvernare_moldova/
    - icon: fontawesome/brands/flickr
      link: https://www.flickr.com/photos/201389958@N05/

extra_css:
  - stylesheets/onest.css

nav:
  - Acasă: index.md
  - Despre: info/about.md
  - Contacte: info/contacts.md

copyright: © Agenția de Guvernare Electronică. Toate drepturile rezervate. 
