site_name: Documentation

theme:
    name: material
    language: ro
    logo: assets/logo.png
    favicon: assets/favicon.ico
plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: ro
          name: Română
          default: true
          build: true
        - locale: en
          name: English
          build: true
          nav_translations:
            Acasă: Home
            Despre: About
extra:
  alternate:
    - name: Română
      link: /
      lang: ro
    - name: English
      link: /en/
      lang: en


nav:
  - Acasă: index.md
  - Despre: info/about.md
  - Contacte: info/contacts.md