@startuml

skinparam shadowing false
skinparam mainframe fontColor #2094F3
skinparam backgroundColor transparent
skinparam actor {
    BorderColor #2094F3
    BackgroundColor #E6E1E3
    FontColor #E6E1E3
    FontStyle bold
}
skinparam sequence {
    ParticipantFontStyle bold
    ParticipantFontColor #1E2129
    ParticipantBorderColor #2094F3
    ParticipantBackgroundColor #E6E1E3
    LifeLineBorderColor #2094F3
    LifeLineBackgroundColor #E6E1E3
    ArrowColor #2094F3
    ArrowFontColor #E6E1E3
    ArrowFontStyle bold
}

participant "3rd System" as IntegratedSystem
participant "API Gateway" as MNotifyAPI
participant MPass

activate IntegratedSystem

IntegratedSystem -> MNotifyAPI: 1. RequestAuthenticationByCertificate()
activate MNotifyAPI

MNotifyAPI -> MPass: RequestAuthenticationByCertificate()
activate MPass

MPass -> MPass: Verify AuthDetails and roles
activate MPass
deactivate MPass

MPass --> MNotifyAPI: :AuthDetails and roles
deactivate MPass

MNotifyAPI -> MNotifyAPI: 3. ActivateSession()
activate MNotifyAPI
deactivate MNotifyAPI


deactivate MNotifyAPI
deactivate IntegratedSystem

@enduml